//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaStorcenterDataA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int TransactionID { get; set; }
        public double TransValue { get; set; }
        public Nullable<int> FK_BillID { get; set; }
        public int UserID { get; set; }
        public int CharityID { get; set; }
        public int TransTypeID { get; set; }
    
        public virtual Charity Charity { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
